/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cse.deu.hms.totalManagement;

import java.io.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SAMSUNG
 */
public class HotelManagement extends javax.swing.JFrame {

    private String paths = System.getProperty("user.dir");  // 프로젝트 루트 경로
    private File roomPriceFile = new File(paths + "/src/roomPrice.txt"); // src폴더에 파일이 있음
    private File menuFile = new File(paths + "/src/menu_list.txt");
    private File userFile = new File(paths + "/src/user_list.txt");

    /**
     * Creates new form HotelManagement
     */
    public HotelManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        room = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        roomCancel = new javax.swing.JButton();
        roomModify = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        menu = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        menuCancel = new javax.swing.JButton();
        menuAdd = new javax.swing.JButton();
        menuDelete = new javax.swing.JButton();
        menuModify = new javax.swing.JButton();
        account = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        menuchange = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        menuAppend = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        accountchange = new javax.swing.JDialog();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        accountAppend = new javax.swing.JDialog();
        jButton7 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        hotelManagementCancel = new javax.swing.JButton();
        roomButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        accountButton = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel2.setText("객실관리");
        jLabel2.setToolTipText("");

        roomCancel.setText("취소");
        roomCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomCancelActionPerformed(evt);
            }
        });

        roomModify.setText("수정");
        roomModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomModifyActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "층수", "금액"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout roomLayout = new javax.swing.GroupLayout(room.getContentPane());
        room.getContentPane().setLayout(roomLayout);
        roomLayout.setHorizontalGroup(
            roomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roomLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(roomLayout.createSequentialGroup()
                        .addComponent(roomCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addComponent(roomModify))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        roomLayout.setVerticalGroup(
            roomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomCancel)
                    .addComponent(roomModify))
                .addContainerGap())
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "메뉴", "금액", "식당 / 룸서비스"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel3.setText("메뉴 관리");
        jLabel3.setToolTipText("");

        menuCancel.setText("취소");
        menuCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCancelActionPerformed(evt);
            }
        });

        menuAdd.setText("추가");
        menuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddActionPerformed(evt);
            }
        });

        menuDelete.setText("삭제");
        menuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeleteActionPerformed(evt);
            }
        });

        menuModify.setText("수정");
        menuModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu.getContentPane());
        menu.getContentPane().setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(menuCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(menuDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menuModify)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menuAdd))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuCancel)
                    .addComponent(menuAdd)
                    .addComponent(menuModify)
                    .addComponent(menuDelete))
                .addContainerGap())
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "고유 문자", "ID", "PASS"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel4.setText("계정 관리");
        jLabel4.setToolTipText("");

        jButton12.setText("취소");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("추가");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("삭제");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("수정");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountLayout = new javax.swing.GroupLayout(account.getContentPane());
        account.getContentPane().setLayout(accountLayout);
        accountLayout.setHorizontalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(accountLayout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                .addContainerGap())
        );
        accountLayout.setVerticalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton13)
                    .addComponent(jButton15)
                    .addComponent(jButton14))
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel5.setText("메뉴 수정");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("메뉴");

        jLabel7.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("금액");

        jLabel8.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("식당 / 룸서비스");

        jButton1.setText("취소");

        jButton2.setText("변경");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "식당", "룸서비스" }));

        javax.swing.GroupLayout menuchangeLayout = new javax.swing.GroupLayout(menuchange.getContentPane());
        menuchange.getContentPane().setLayout(menuchangeLayout);
        menuchangeLayout.setHorizontalGroup(
            menuchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuchangeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5))
            .addGroup(menuchangeLayout.createSequentialGroup()
                .addGroup(menuchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuchangeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(menuchangeLayout.createSequentialGroup()
                        .addGroup(menuchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuchangeLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(menuchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuchangeLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(menuchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox1, 0, 93, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap())
        );
        menuchangeLayout.setVerticalGroup(
            menuchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuchangeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(menuchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menuchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menuchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(menuchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("금액");

        jLabel10.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("식당 / 룸서비스");

        jButton3.setText("취소");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("추가");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "식당", "룸서비스" }));

        jLabel11.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel11.setText("메뉴 추가");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("메뉴");

        javax.swing.GroupLayout menuAppendLayout = new javax.swing.GroupLayout(menuAppend.getContentPane());
        menuAppend.getContentPane().setLayout(menuAppendLayout);
        menuAppendLayout.setHorizontalGroup(
            menuAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAppendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11))
            .addGroup(menuAppendLayout.createSequentialGroup()
                .addGroup(menuAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuAppendLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(menuAppendLayout.createSequentialGroup()
                        .addGroup(menuAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuAppendLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(menuAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuAppendLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18)
                        .addGroup(menuAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox2, 0, 93, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap())
        );
        menuAppendLayout.setVerticalGroup(
            menuAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAppendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(menuAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menuAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menuAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(menuAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        jButton5.setText("변경");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel13.setText("계정 수정");

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel14.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ID");

        jLabel15.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("PASS");

        jButton6.setText("취소");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountchangeLayout = new javax.swing.GroupLayout(accountchange.getContentPane());
        accountchange.getContentPane().setLayout(accountchangeLayout);
        accountchangeLayout.setHorizontalGroup(
            accountchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountchangeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountchangeLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(accountchangeLayout.createSequentialGroup()
                        .addGroup(accountchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(accountchangeLayout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addComponent(jButton5))
                            .addGroup(accountchangeLayout.createSequentialGroup()
                                .addGroup(accountchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(accountchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        accountchangeLayout.setVerticalGroup(
            accountchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountchangeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(30, 30, 30)
                .addGroup(accountchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(accountchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(accountchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jButton7.setText("추가");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E" }));

        jLabel17.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel17.setText("계정 추가");

        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel18.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("ID");

        jLabel19.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("PASS");

        jLabel20.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("고유 문자");

        jButton8.setText("취소");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountAppendLayout = new javax.swing.GroupLayout(accountAppend.getContentPane());
        accountAppend.getContentPane().setLayout(accountAppendLayout);
        accountAppendLayout.setHorizontalGroup(
            accountAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountAppendLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountAppendLayout.createSequentialGroup()
                        .addGroup(accountAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(accountAppendLayout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addComponent(jButton7))
                            .addGroup(accountAppendLayout.createSequentialGroup()
                                .addGroup(accountAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(accountAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7)
                                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(17, 17, 17)))
                        .addContainerGap())
                    .addGroup(accountAppendLayout.createSequentialGroup()
                        .addGroup(accountAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(accountAppendLayout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField8)))
                        .addGap(23, 23, 23))))
        );
        accountAppendLayout.setVerticalGroup(
            accountAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountAppendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(27, 27, 27)
                .addGroup(accountAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(accountAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(accountAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(accountAppendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        jLabel1.setText("호텔 관리");

        hotelManagementCancel.setText("취소");
        hotelManagementCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelManagementCancelActionPerformed(evt);
            }
        });

        roomButton.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        roomButton.setText("객실");
        roomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomButtonActionPerformed(evt);
            }
        });

        menuButton.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        menuButton.setText("메뉴");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        accountButton.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        accountButton.setText("계정");
        accountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hotelManagementCancel, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(accountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(menuButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                .addComponent(roomButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addComponent(roomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(accountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(hotelManagementCancel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hotelManagementCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelManagementCancelActionPerformed
        dispose();   // 취소버튼
    }//GEN-LAST:event_hotelManagementCancelActionPerformed

    private void roomCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomCancelActionPerformed
        // TODO add your handling code here:
        room.dispose();
    }//GEN-LAST:event_roomCancelActionPerformed

    private void menuCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCancelActionPerformed
        // TODO add your handling code here:
        menu.dispose();
    }//GEN-LAST:event_menuCancelActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        account.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void roomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomButtonActionPerformed
        // TODO add your handling code here:
        room.setSize(400, 350); // 너비 400, 높이 500으로 설정
        room.setResizable(false); // 크기 변경 불가능하도록 설정 (선택 사항)
        room.setLocationRelativeTo(this);// 다이얼로그를 화면 중앙에 위치
        room.setVisible(true);// 다이얼로그 표시

        // room 테이블의 모델 가져오기
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // 기존 데이터 초기화

        // roomPrice.txt 파일 읽기
        try (BufferedReader br = new BufferedReader(new FileReader(roomPriceFile))) {
            String line;
            while ((line = br.readLine()) != null) {
                // 파일 내용이 "층수, 금액" 형식으로 저장되어 있다고 가정
                String[] data = line.split("\t");
                if (data.length == 2) {
                    model.addRow(new Object[]{data[0].trim(), data[1].trim()}); // 테이블에 행 추가
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "파일 읽기 실패: " + e.getMessage(), "오류", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_roomButtonActionPerformed

    private void roomModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomModifyActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            String floor = (String) jTable1.getValueAt(selectedRow, 0); // 층수
            String currentPrice = (String) jTable1.getValueAt(selectedRow, 1); // 현재 금액

            // 금액 수정 입력창 생성
            String newPrice = JOptionPane.showInputDialog(this,
                    "현재 금액: " + currentPrice + "\n금액을 수정하십시오:",
                    "금액 수정",
                    JOptionPane.PLAIN_MESSAGE);

            // 새 금액이 입력되었을 경우 업데이트
            if (newPrice != null && !newPrice.trim().isEmpty()) {
                // 테이블에서 금액 수정
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setValueAt(newPrice.trim(), selectedRow, 1);

                // 파일에서도 금액 수정
                updateFileAfterEdit(floor, newPrice.trim());
            }
        } else {
            JOptionPane.showMessageDialog(this, "수정할 층을 선택하십시오.", "오류", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_roomModifyActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
        menu.setSize(430, 350); // 너비 400, 높이 500으로 설정
        menu.setResizable(false); // 크기 변경 불가능하도록 설정 (선택 사항)
        menu.setLocationRelativeTo(this);// 다이얼로그를 화면 중앙에 위치
        menu.setVisible(true);// 다이얼로그 표시

        loadMenuData();
    }//GEN-LAST:event_menuButtonActionPerformed
    private void loadMenuData() {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0); // 기존 데이터 초기화

        try (BufferedReader reader = new BufferedReader(new FileReader(menuFile))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] data = line.split("\t"); // 탭으로 구분된 데이터
                if (data.length == 3) {
                    model.addRow(new Object[]{data[0].trim(), data[1].trim(), data[2].trim()});
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "파일 읽기 실패: " + e.getMessage(), "오류", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadAccountData() {
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0); // 기존 데이터 초기화

        try (BufferedReader reader = new BufferedReader(new FileReader(userFile))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] data = line.split("\t"); // 탭으로 구분된 데이터
                if (data.length == 3) { // 고유 문자, ID, PASS
                    model.addRow(new Object[]{data[0].trim(), data[1].trim(), data[2].trim()});
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "파일 읽기 실패: " + e.getMessage(), "오류", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void menuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable2.getSelectedRow(); // 선택된 행 가져오기
        if (selectedRow != -1) {
            // 테이블에서 데이터를 가져옴
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            String menuName = (String) model.getValueAt(selectedRow, 0); // 메뉴 이름
            String price = (String) model.getValueAt(selectedRow, 1); // 금액
            String type = (String) model.getValueAt(selectedRow, 2); // 식당/룸서비스 정보

            // 선택된 행 삭제
            model.removeRow(selectedRow);

            // 파일 업데이트 (삭제된 메뉴 제외하고 다시 저장)
            updateMenuFile(menuName, price, type);
        } else {
            JOptionPane.showMessageDialog(this, "삭제할 행을 선택하세요.", "오류", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_menuDeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void menuModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModifyActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable2.getSelectedRow(); // 선택된 행 가져오기
        if (selectedRow != -1) {
            // 선택된 행 데이터 가져오기
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            String menuName = (String) model.getValueAt(selectedRow, 0); // 메뉴 이름
            String price = (String) model.getValueAt(selectedRow, 1);    // 금액
            String type = (String) model.getValueAt(selectedRow, 2);    // 식당/룸서비스

            // 다이얼로그에 값 설정
            jTextField1.setText(menuName);
            jTextField2.setText(price);
            jComboBox1.setSelectedItem(type); // 식당 또는 룸서비스 선택

            // 메뉴 이름 비활성화 (수정 불가)
            jTextField1.setEnabled(false);

            // 다이얼로그 열기
            menuchange.setSize(418, 305);
            menuchange.setResizable(false);
            menuchange.setLocationRelativeTo(this);
            menuchange.setVisible(true);

            // 다이얼로그에서 "변경" 버튼 클릭 시 동작
            jButton2.addActionListener(e -> {
                String newPrice = jTextField2.getText().trim();
                String newType = (String) jComboBox1.getSelectedItem();

                // 필수 데이터 확인
                if (newPrice.isEmpty() || newType.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "모든 필드를 입력하세요.", "오류", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                // 테이블 데이터 업데이트 (메뉴 이름은 수정하지 않음)
                model.setValueAt(newPrice, selectedRow, 1);
                model.setValueAt(newType, selectedRow, 2);

                // 파일 데이터 업데이트
                updateMenuFile(menuName, price, type, menuName, newPrice, newType);

                // 다이얼로그 닫기
                menuchange.dispose();
            });

            // 다이얼로그에서 "취소" 버튼 클릭 시 동작
            jButton1.addActionListener(e -> menuchange.dispose());
        } else {
            JOptionPane.showMessageDialog(this, "수정할 행을 선택하세요.", "오류", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_menuModifyActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String menuName = jTextField4.getText().trim(); // 메뉴 이름
        String menuPrice = jTextField3.getText().trim(); // 메뉴 가격
        String menuType = (String) jComboBox2.getSelectedItem(); // 식당/룸서비스 구분

        // 입력값 검증
        if (menuName.isEmpty() || menuPrice.isEmpty() || menuType.isEmpty()) {
            JOptionPane.showMessageDialog(this, "모든 필드를 입력하세요.", "오류", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 중복 검사
        if (isMenuDuplicate(menuName, menuType)) {
            JOptionPane.showMessageDialog(this, "이미 존재하는 메뉴입니다. 다른 메뉴 이름을 입력하세요.", "중복 오류", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 파일에 추가
        try {
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(menuFile, true))) {
                writer.write(menuName + "\t" + menuPrice + "\t" + menuType);
                writer.newLine();
            }

            // 테이블에 추가
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.addRow(new Object[]{menuName, menuPrice, menuType});

            // 입력 필드 초기화
            jTextField4.setText("");
            jTextField3.setText("");

            // 다이얼로그 닫기
            menuAppend.dispose();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "메뉴 추가 중 오류 발생: " + e.getMessage(), "오류", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private boolean isMenuDuplicate(String menuName, String menuType) {
        try (BufferedReader reader = new BufferedReader(new FileReader(menuFile))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] data = line.split("\t"); // 데이터는 탭으로 구분되어 있음
                if (data.length == 3) {
                    String existingMenuName = data[0].trim();
                    String existingMenuType = data[2].trim();
                    if (existingMenuName.equals(menuName) && existingMenuType.equals(menuType)) {
                        return true; // 중복 메뉴 발견
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "파일 읽기 중 오류 발생: " + e.getMessage(), "오류", JOptionPane.ERROR_MESSAGE);
        }
        return false; // 중복 없음
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        menuAppend.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void menuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddActionPerformed
        // TODO add your handling code here:
        menuAppend.setSize(400, 300); // 다이얼로그 크기 설정
        menuAppend.setResizable(false); // 크기 조정 불가
        menuAppend.setLocationRelativeTo(this); // 화면 중앙에 위치
        menuAppend.setVisible(true); // 다이얼로그 표시
    }//GEN-LAST:event_menuAddActionPerformed

    private void accountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountButtonActionPerformed
        // TODO add your handling code here:
        account.setSize(450, 400); // 다이얼로그 크기 설정
        account.setResizable(false); // 크기 조정 불가
        account.setLocationRelativeTo(this); // 화면 중앙에 위치
        account.setVisible(true); // 다이얼로그 표시
        loadAccountData(); // 계정 데이터 로드
    }//GEN-LAST:event_accountButtonActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable3.getSelectedRow(); // 선택된 행 가져오기
        if (selectedRow != -1) {
            // 테이블에서 데이터를 가져옴
            DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
            String uniqueCode = (String) model.getValueAt(selectedRow, 0); // 고유 문자
            String id = (String) model.getValueAt(selectedRow, 1); // ID
            String pass = (String) model.getValueAt(selectedRow, 2); // PASS

            // 선택된 행 삭제
            model.removeRow(selectedRow);

            // 파일에서 데이터 삭제
            deleteFromUserFile(uniqueCode, id, pass);
        } else {
            JOptionPane.showMessageDialog(this, "삭제할 행을 선택하세요.", "오류", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void deleteFromUserFile(String uniqueCode, String id, String pass) {
        try {
            // 파일 내용을 메모리에 저장
            StringBuilder content = new StringBuilder();
            try (BufferedReader reader = new BufferedReader(new FileReader(userFile))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String[] data = line.split("\t"); // 탭으로 구분된 데이터
                    if (data.length == 3) {
                        // 삭제할 데이터와 일치하지 않으면 유지
                        if (!data[0].trim().equals(uniqueCode) || !data[1].trim().equals(id) || !data[2].trim().equals(pass)) {
                            content.append(line).append(System.lineSeparator());
                        }
                    }
                }
            }

            // 파일 업데이트 (삭제된 데이터 제외하고 다시 저장)
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(userFile))) {
                writer.write(content.toString());
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "파일 업데이트 중 오류 발생: " + e.getMessage(), "오류", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable3.getSelectedRow(); // 선택된 행 가져오기
        if (selectedRow != -1) {
            // 테이블에서 데이터 가져오기
            DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
            String selectedId = (String) model.getValueAt(selectedRow, 1); // ID
            String currentPass = (String) model.getValueAt(selectedRow, 2); // PASS

            // 수정 다이얼로그 초기 설정
            jTextField5.setText(selectedId); // ID 입력 필드에 값 설정 (수정 불가)
            jTextField5.setEnabled(false);
            jTextField6.setText(currentPass); // PASS 입력 필드에 값 설정

            // 다이얼로그 열기
            accountchange.setSize(300, 200);
            accountchange.setResizable(false);
            accountchange.setLocationRelativeTo(this);
            accountchange.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "수정할 계정을 선택하세요.", "오류", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void updateAccountFile(String id, String oldPass, String newPass) {
        try {
            StringBuilder content = new StringBuilder();
            try (BufferedReader reader = new BufferedReader(new FileReader(userFile))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String[] data = line.split("\t"); // 탭으로 구분된 데이터
                    if (data.length == 3) {
                        // 수정 대상인 경우 PASS 업데이트
                        if (data[1].trim().equals(id) && data[2].trim().equals(oldPass)) {
                            content.append(data[0]).append("\t") // 고유 문자
                                    .append(data[1]).append("\t") // ID
                                    .append(newPass).append(System.lineSeparator()); // 새로운 PASS
                        } else {
                            content.append(line).append(System.lineSeparator()); // 기존 데이터 유지
                        }
                    }
                }
            }

            // 파일에 수정된 내용 저장
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(userFile))) {
                writer.write(content.toString());
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "파일 수정 중 오류 발생: " + e.getMessage(), "오류", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        accountAppend.setSize(300, 300); // 다이얼로그 크기 설정
        accountAppend.setResizable(false); // 크기 조정 불가
        accountAppend.setLocationRelativeTo(this); // 화면 중앙에 위치
        accountAppend.setVisible(true); // 다이얼로그 표시

        // 고유 문자 E 고정
        jComboBox4.setSelectedItem("E");
        jComboBox4.setEnabled(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable3.getSelectedRow(); // 선택된 행 가져오기
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
            String selectedId = (String) model.getValueAt(selectedRow, 1); // ID
            String currentPass = (String) model.getValueAt(selectedRow, 2); // 현재 PASS

            // 새로운 PASS 가져오기
            String newPass = jTextField6.getText().trim();
            if (newPass.isEmpty()) {
                JOptionPane.showMessageDialog(this, "PASS를 입력하세요.", "오류", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 테이블 데이터 업데이트
            model.setValueAt(newPass, selectedRow, 2);

            // 파일 데이터 업데이트
            updateAccountFile(selectedId, currentPass, newPass);

            // 다이얼로그 닫기
            accountchange.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "수정할 계정을 선택하세요.", "오류", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        accountchange.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String uniqueCode = (String) jComboBox4.getSelectedItem(); // 고유 문자
        String newId = jTextField7.getText().trim(); // ID 입력 필드에서 값 가져오기
        String newPass = jTextField8.getText().trim(); // PASS 입력 필드에서 값 가져오기

        // 입력값 검증
        if (newId.isEmpty() || newPass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "모든 필드를 입력하세요.");
            return;
        }

        // 중복 검사
        if (isIdDuplicate(newId)) {
            JOptionPane.showMessageDialog(this, "이미 존재하는 ID입니다.");
            return;
        }

        // 파일에 추가
        try {
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(userFile, true))) {
                writer.write(uniqueCode + "\t" + newId + "\t" + newPass);
                writer.newLine();
            }

            // 테이블에 추가
            DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
            model.addRow(new Object[]{uniqueCode, newId, newPass});

            // 성공 메시지
            JOptionPane.showMessageDialog(this, "계정이 추가되었습니다.");

            // 입력 필드 초기화
            jTextField7.setText("");
            jTextField8.setText("");

            // 다이얼로그 닫기
            accountAppend.dispose();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "계정 추가 중 오류 발생: " + e.getMessage(), "오류", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private boolean isIdDuplicate(String newId) {
        try (BufferedReader reader = new BufferedReader(new FileReader(userFile))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] data = line.split("\t"); // 데이터는 탭으로 구분되어 있음
                if (data.length >= 2) {
                    String existingId = data[1].trim(); // 파일에서 ID 가져오기
                    if (existingId.equals(newId)) {
                        return true; // 중복 ID 발견
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "파일 읽기 중 오류 발생: " + e.getMessage(), "오류", JOptionPane.ERROR_MESSAGE);
        }
        return false; // 중복 없음
    }

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        accountAppend.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void updateMenuFile(String oldMenu, String oldPrice, String oldType,
            String newMenu, String newPrice, String newType) {
        try {
            StringBuilder content = new StringBuilder();
            try (BufferedReader reader = new BufferedReader(new FileReader(menuFile))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String[] data = line.split("\t");
                    if (data.length == 3) {
                        // 기존 데이터와 일치하면 수정된 데이터로 교체 (메뉴 이름은 동일)
                        if (data[0].trim().equals(oldMenu)
                                && data[1].trim().equals(oldPrice)
                                && data[2].trim().equals(oldType)) {
                            content.append(oldMenu).append("\t") // 메뉴 이름 그대로
                                    .append(newPrice).append("\t")
                                    .append(newType).append(System.lineSeparator());
                        } else {
                            // 기존 데이터를 유지
                            content.append(line).append(System.lineSeparator());
                        }
                    }
                }
            }

            // 수정된 내용을 파일에 저장
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(menuFile))) {
                writer.write(content.toString());
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "파일 수정 중 오류 발생: " + e.getMessage(), "오류", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateMenuFile(String menuName, String price, String type) {
        try {
            // 파일의 내용을 메모리에 로드
            StringBuilder content = new StringBuilder();
            try (BufferedReader reader = new BufferedReader(new FileReader(menuFile))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String[] data = line.split("\t");
                    if (data.length == 3) {
                        // 삭제할 데이터와 일치하지 않는 경우만 저장
                        if (!data[0].trim().equals(menuName)
                                || !data[1].trim().equals(price)
                                || !data[2].trim().equals(type)) {
                            content.append(line).append(System.lineSeparator());
                        }
                    }
                }
            }

            // 수정된 내용을 파일에 저장
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(menuFile))) {
                writer.write(content.toString());
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "파일 업데이트 중 오류 발생: " + e.getMessage(), "오류", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateFileAfterEdit(String floorToEdit, String newPrice) {
        try {
            // 파일의 내용을 메모리에 로드
            StringBuilder content = new StringBuilder();
            try (BufferedReader reader = new BufferedReader(new FileReader(roomPriceFile))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String[] data = line.split("\t");
                    if (data[0].trim().equals(floorToEdit)) {
                        // 해당 층수의 금액만 수정
                        content.append(floorToEdit).append("\t").append(newPrice).append(System.lineSeparator());
                    } else {
                        // 나머지 데이터는 그대로 유지
                        content.append(line).append(System.lineSeparator());
                    }
                }
            }

            // 수정된 내용을 파일에 덮어쓰기
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(roomPriceFile))) {
                writer.write(content.toString());
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "파일 수정 중 오류 발생: " + e.getMessage(), "오류", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog account;
    private javax.swing.JDialog accountAppend;
    private javax.swing.JButton accountButton;
    private javax.swing.JDialog accountchange;
    private javax.swing.JButton hotelManagementCancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JDialog menu;
    private javax.swing.JButton menuAdd;
    private javax.swing.JDialog menuAppend;
    private javax.swing.JButton menuButton;
    private javax.swing.JButton menuCancel;
    private javax.swing.JButton menuDelete;
    private javax.swing.JButton menuModify;
    private javax.swing.JDialog menuchange;
    private javax.swing.JDialog room;
    private javax.swing.JButton roomButton;
    private javax.swing.JButton roomCancel;
    private javax.swing.JButton roomModify;
    // End of variables declaration//GEN-END:variables
}
